name = "NeuroStudies"
uuid = "80a1f922-8ff7-4b10-86fa-6baadcfd06d1"
authors = ["Zachary P. Christensen <zchristensen7@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Metadata = "4fb893c1-3164-4f58-823a-cb4c64eabb4f"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
JSON3 = "1"
Metadata = "0.2, 0.3"
OrderedCollections = "1"
Tables = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
